services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: leo
      POSTGRES_PASSWORD: secret12345
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
    volumes:
      - local_db_data:/var/lib/postgresql/data
  
  fastapi_app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  local_db_data: