"""Create User table

Revision ID: 24c00a278842
Revises: c4e710c8fc90
Create Date: 2025-07-28 19:13:33.283738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # importing sqlmodel for SQLModel support


# revision identifiers, used by Alembic.
revision: str = '24c00a278842'
down_revision: Union[str, Sequence[str], None] = 'c4e710c8fc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
